#!/usr/bin/env python3
"""Generate docs/options.md from the CLI itself.

The recurring complaint in JOSS review openjournals/joss-reviews#10532 was that
the documentation did not describe what the software actually did: option
tables were incomplete, file counts were wrong, and --img-format was not
mentioned anywhere despite existing. Hand-maintained reference tables drift.

This renders the reference straight from the parser, and
tests/test_generated_docs.py fails when the committed file no longer matches,
so the two cannot silently diverge.

Usage:
    python scripts/generate_options_doc.py          # write docs/options.md
    python scripts/generate_options_doc.py --check  # exit 1 if it is stale
"""

import argparse
import sys
from pathlib import Path

from cogstim.cli import create_parser
from cogstim.helpers import cli_options as opts
from cogstim.helpers.cli_options import Option

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "docs" / "options.md"

HEADER = """# Options reference

<!--
  Generated by scripts/generate_options_doc.py. Do not edit by hand.
  Run `python scripts/generate_options_doc.py` after changing any option.
-->

Every option of every task, taken directly from the command-line parser.

`--train-num` and `--test-num` count **sets**, not images; see
[Sets and images](guide.md#sets-and-images). Use `--dry-run` to see how many
images a particular command would write.
"""


def format_value(value):
    """Render a default value for a documentation table."""
    if value is None:
        return "*(chosen automatically)*"
    if value == "":
        return "*(empty)*"
    if isinstance(value, (list, tuple)):
        return "`" + " ".join(str(v) for v in value) + "`"
    if isinstance(value, bool):
        return "off" if value is False else "on"
    return f"`{value}`"


def subcommand_sections(parser):
    """Yield a markdown section for each subcommand."""
    subparsers = [
        action for action in parser._actions
        if isinstance(action, argparse._SubParsersAction)
    ][0]

    for name in sorted(subparsers.choices):
        sub = subparsers.choices[name]
        lines = [f"\n## `cogstim {name}`\n"]
        if sub.description:
            lines.append(f"{sub.description}\n")

        lines.append("| Option | Default | Choices | Description |")
        lines.append("|---|---|---|---|")

        actions = [a for a in sub._actions if a.dest != "help" and a.option_strings]
        for action in sorted(actions, key=lambda a: a.option_strings[0]):
            flag = action.option_strings[0]
            choices = (
                ", ".join(f"`{c}`" for c in action.choices) if action.choices else ""
            )
            help_text = (action.help or "").replace("|", "\\|")
            lines.append(
                f"| `{flag}` | {format_value(action.default)} | {choices} | {help_text} |"
            )
        yield "\n".join(lines) + "\n"


def deprecated_section():
    """Render the migration table for renamed options."""
    renames = []
    for value in vars(opts).values():
        candidates = value if isinstance(value, list) else [value]
        for option in candidates:
            if isinstance(option, Option) and option.aliases:
                for alias in option.aliases:
                    renames.append((alias, option.name))

    if not renames:
        return ""

    lines = [
        "\n## Renamed options\n",
        "These older spellings still work and will keep working, but they emit a",
        "deprecation warning. Prefer the new name.\n",
        "| Old name | Use instead |",
        "|---|---|",
    ]
    for old, new in sorted(set(renames)):
        lines.append(f"| `{old}` | `{new}` |")
    return "\n".join(lines) + "\n"


def render() -> str:
    """Build the complete options reference."""
    parser = create_parser()
    return HEADER + "".join(subcommand_sections(parser)) + deprecated_section()


def main() -> int:
    check_only = "--check" in sys.argv
    content = render()

    if check_only:
        if not OUTPUT_PATH.exists():
            print(f"{OUTPUT_PATH} is missing; run scripts/generate_options_doc.py")
            return 1
        if OUTPUT_PATH.read_text(encoding="utf-8") != content:
            print(
                f"{OUTPUT_PATH} is out of date with the CLI.\n"
                "Run: python scripts/generate_options_doc.py"
            )
            return 1
        print(f"{OUTPUT_PATH} is up to date")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
